
package com.catic.mobilehos.webservice.timing;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-08-14T17:36:27.993+08:00
 * Generated source version: 2.7.12
 * 
 */
public final class TimingService_TimingServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.timing.webService.mobilehos.catic.com/", "TimingServiceImplService");

    private TimingService_TimingServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TimingServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TimingServiceImplService ss = new TimingServiceImplService(wsdlURL, SERVICE_NAME);
        TimingService port = ss.getTimingServiceImplPort();  
        
        {
        System.out.println("Invoking getAppRegPeriod...");
        java.lang.String _getAppRegPeriod__return = port.getAppRegPeriod();
        System.out.println("getAppRegPeriod.result=" + _getAppRegPeriod__return);


        }
        {
        System.out.println("Invoking getDoctors...");
        java.lang.String _getDoctors__return = port.getDoctors();
        System.out.println("getDoctors.result=" + _getDoctors__return);


        }
        {
        System.out.println("Invoking getHisDepartmentDoctor...");
        java.lang.String _getHisDepartmentDoctor__return = port.getHisDepartmentDoctor();
        System.out.println("getHisDepartmentDoctor.result=" + _getHisDepartmentDoctor__return);


        }
        {
        System.out.println("Invoking getHisRoomQueueSn...");
        java.lang.String _getHisRoomQueueSn__return = port.getHisRoomQueueSn();
        System.out.println("getHisRoomQueueSn.result=" + _getHisRoomQueueSn__return);


        }
        {
        System.out.println("Invoking getAppRegOrderType...");
        java.lang.String _getAppRegOrderType__return = port.getAppRegOrderType();
        System.out.println("getAppRegOrderType.result=" + _getAppRegOrderType__return);


        }
        {
        System.out.println("Invoking getTimetable...");
        java.lang.String _getTimetable_arg0 = "";
        java.lang.String _getTimetable__return = port.getTimetable(_getTimetable_arg0);
        System.out.println("getTimetable.result=" + _getTimetable__return);


        }
        {
        System.out.println("Invoking getHisAppRegException...");
        java.lang.String _getHisAppRegException_arg0 = "";
        java.lang.String _getHisAppRegException__return = port.getHisAppRegException(_getHisAppRegException_arg0);
        System.out.println("getHisAppRegException.result=" + _getHisAppRegException__return);


        }
        {
        System.out.println("Invoking getDepartments...");
        java.lang.String _getDepartments__return = port.getDepartments();
        System.out.println("getDepartments.result=" + _getDepartments__return);


        }
        {
        System.out.println("Invoking getRooms...");
        java.lang.String _getRooms__return = port.getRooms();
        System.out.println("getRooms.result=" + _getRooms__return);


        }

        System.exit(0);
    }

}
